version: '3.3'
services:
  rails:
    build: .
    command: bash -c "rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./app:/opt/app
    tty: true
    hostname: rails
  db:
    image: mariadb:10.5.8
    hostname: db
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - "3306"
    volumes:
      - "./data/db:/var/lib/mysql"
